# ----
# Site

title: UM::Autonomy
url: "https://umautonomy.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/favicon-512.png
description: Official website for UM Autonomy
author:
  name: UM Autonomy
  email: umautonomy@umich.edu
  twitter: https://twitter.com/UMAutonomy

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor

collections:
  team_members:
    _hide_content: true
    _icon: account_circle
  teams:
  sponsors:
  boats:
  projects:
  roboboat:
  process:

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ["categories"]

defaults:
  - scope:
      path: ""
      type: "team_members"
    values:
      _options:
        image_path:
          width: 440
          height: 440
          uploads_dir: "/images/team_members"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
          uploads_dir: "/images/post_uploads"
        content:
          width: 1500
          height: 2000
          uploads_dir: "/images/post_uploads"
  - scope:
      path: "contact-success.html"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: The official UM Autonomy website
  blurb: Learn more about UMA here!
